### ISSUE TITLE
adding syntax highlighting for more languages

### ISSUE THREAD

**Issue by adielbm** [typhoon-kim/obsidian-svelte-syntax-highlighter#1]
I thought it'd be great if this plugin had an option to add highlighting for additional languages. (In my case, I wanted MIPS Assembly). 

anyway, I forked your repo, added MIPS Assembly syntax highlighting, made some changes, and it's working! I won’t publish my code in the community plugins because there might be some bugs—I’m not an expert at this. I thought it’d be nice to share it with you. I also credited you in the README, and I hope that’s okay with you. https://github.com/adielBm/obsidian-hl

Thanks!

**Comment by typhoon-kim** [comment]
@adielBm
Thank you for your thoughtful comment and for exploring ways to enhance this plugin! I'm truly glad if this repository has been helpful to you.

Your idea of adding additional syntax highlighting is excellent. However, I've considered a few issues. For one, renaming the plugin isn't straightforward. Also, users might have varied needs for instance, those wanting MIPS Assembly support might not need Svelte syntax and may avoid the plugin entirely even if options are provided.

Considering these points, I suggest distributing your fork as a new plugin. It already scalability, and with a brief guide or examples, users could easily add and register new language highlights.

Once again, thank you for your interest and for sharing your work. 👏
